## ##YAML Template
default: --profile html_report --profile chrome --profile dev
html_report: --format progress --format html --out=features_report.html
firefox: BROWSER=firefox
chrome: BROWSER=chrome
poltergeist: BROWSER=poltergeist
internet_explorer: BROWSER=internet_explorer
safari: BROWSER=safari
dev: ENVIRONMENT_TYPE=dev
stage: ENVIRONMENT_TYPE=stage
headless: MODO_HEADLESS=true